// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:mobilechat/utils/constants/api.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Apikeys.webApiKey,
    appId: Apikeys.webAppId,
    messagingSenderId: Apikeys.webMessagingSenderId,
    projectId: Apikeys.webProjectId,
    authDomain: Apikeys.webAuthDomain,
    storageBucket: Apikeys.webStorageBucket,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Apikeys.androidApiKey,
    appId: Apikeys.androidAppId,
    messagingSenderId: Apikeys.androidMessagingSenderId,
    projectId: Apikeys.androidProjectId,
    storageBucket: Apikeys.androidStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Apikeys.iosApiKey,
    appId: Apikeys.iosAppId,
    messagingSenderId: Apikeys.iosMessagingSenderId,
    projectId: Apikeys.iosProjectId,
    storageBucket: Apikeys.iosStorageBucket,
    iosBundleId: Apikeys.iosBundleId,
  );

  static const FirebaseOptions macos = FirebaseOptions(
      apiKey: Apikeys.macApiKey,
      appId: Apikeys.macAppId,
      messagingSenderId: Apikeys.macMessagingSenderId,
      projectId: Apikeys.macProjectId,
      storageBucket: Apikeys.macStorageBucket,
      iosBundleId: Apikeys.macBundleId,
    );


}
